import {
  Bot,
  Boxes,
  BrainCircuit,
  Building2,
  ChartColumn,
  CircleCheck,
  ClipboardCheck,
  Clock,
  CodeXml,
  Compass,
  Eye,
  Factory,
  FileSearch,
  FileSpreadsheet,
  GraduationCap,
  Handshake,
  HeartPulse,
  Hourglass,
  Landmark,
  LayoutDashboard,
  Lightbulb,
  type LucideIcon,
  MapPin,
  MessagesSquare,
  Network,
  Plug,
  Rocket,
  Ruler,
  Scale,
  Shield,
  Shirt,
  Sparkles,
  Store,
  Target,
  TrendingUp,
  TriangleAlert,
  Truck,
  Unplug,
  Users,
  Wrench,
} from "lucide-react";

// One icon vocabulary for every marketing page block (lucide only).
export const blockIcons = {
  bot: Bot,
  boxes: Boxes,
  brain: BrainCircuit,
  building: Building2,
  chart: ChartColumn,
  check: CircleCheck,
  clipboard: ClipboardCheck,
  clock: Clock,
  code: CodeXml,
  compass: Compass,
  eye: Eye,
  factory: Factory,
  fileSearch: FileSearch,
  sheet: FileSpreadsheet,
  education: GraduationCap,
  handshake: Handshake,
  health: HeartPulse,
  hourglass: Hourglass,
  finance: Landmark,
  dashboard: LayoutDashboard,
  idea: Lightbulb,
  pin: MapPin,
  messages: MessagesSquare,
  network: Network,
  plug: Plug,
  rocket: Rocket,
  ruler: Ruler,
  scale: Scale,
  shield: Shield,
  shirt: Shirt,
  sparkles: Sparkles,
  store: Store,
  target: Target,
  trend: TrendingUp,
  alert: TriangleAlert,
  truck: Truck,
  unplug: Unplug,
  users: Users,
  wrench: Wrench,
} satisfies Record<string, LucideIcon>;

export type BlockIcon = keyof typeof blockIcons;
