import type { WorkflowContent } from "./workflow.types";

const cta = { label: "Book a discovery call", href: "/#contact" } as const;

const workflowContent = {
  title: "How we work",
  description: "Discover → Design → Build → Automate → Improve",
  steps: [
    {
      id: "discover",
      tabLabel: "Discover",
      stepLabel: "Step 01",
      title: "Discover",
      description:
        "We understand how the business operates today, including its processes, people, tools, bottlenecks, and data.",
      cta,
      nodes: [
        {
          id: "processes",
          label: "Processes",
          detail: "12 mapped",
          status: "done",
          x: 22,
          y: 18,
        },
        {
          id: "people",
          label: "People & roles",
          detail: "Interviews done",
          status: "done",
          x: 22,
          y: 52,
        },
        {
          id: "tools",
          label: "Tools audit",
          detail: "9 systems found",
          status: "active",
          x: 70,
          y: 30,
        },
        {
          id: "bottlenecks",
          label: "Bottlenecks",
          detail: "4 identified",
          status: "active",
          x: 70,
          y: 66,
        },
        {
          id: "data",
          label: "Data sources",
          detail: "Reviewing",
          status: "todo",
          x: 22,
          y: 86,
        },
      ],
      edges: [
        ["processes", "people"],
        ["people", "tools"],
        ["people", "bottlenecks"],
        ["people", "data"],
      ],
    },
    {
      id: "design",
      tabLabel: "Design",
      stepLabel: "Step 02",
      title: "Design",
      description:
        "We identify opportunities for automation and design a system around the actual business requirements.",
      cta,
      nodes: [
        {
          id: "requirements",
          label: "Requirements",
          detail: "Signed off",
          status: "done",
          x: 22,
          y: 30,
        },
        {
          id: "automations",
          label: "Automation map",
          detail: "7 opportunities",
          status: "active",
          x: 70,
          y: 18,
        },
        {
          id: "architecture",
          label: "System design",
          detail: "In review",
          status: "active",
          x: 70,
          y: 50,
        },
        {
          id: "roadmap",
          label: "Roadmap",
          detail: "Phase 1 of 3",
          status: "todo",
          x: 70,
          y: 82,
        },
        {
          id: "priorities",
          label: "Priorities",
          detail: "By impact",
          status: "done",
          x: 22,
          y: 70,
        },
      ],
      edges: [
        ["requirements", "automations"],
        ["requirements", "architecture"],
        ["priorities", "roadmap"],
        ["requirements", "priorities"],
      ],
    },
    {
      id: "build",
      tabLabel: "Build",
      stepLabel: "Step 03",
      title: "Build",
      description:
        "We develop the software, integrations, dashboards, and AI capabilities required.",
      cta,
      nodes: [
        {
          id: "software",
          label: "Software",
          detail: "Core app ready",
          status: "done",
          x: 22,
          y: 24,
        },
        {
          id: "integrations",
          label: "Integrations",
          detail: "CRM + ERP",
          status: "active",
          x: 70,
          y: 24,
        },
        {
          id: "ai",
          label: "AI capabilities",
          detail: "Document agent",
          status: "active",
          x: 70,
          y: 62,
        },
        {
          id: "dashboards",
          label: "Dashboards",
          detail: "Up next",
          status: "todo",
          x: 22,
          y: 72,
        },
      ],
      edges: [
        ["software", "integrations"],
        ["integrations", "ai"],
        ["ai", "dashboards"],
      ],
    },
    {
      id: "automate",
      tabLabel: "Automate",
      stepLabel: "Step 04",
      title: "Automate",
      description:
        "We connect the systems and automate repetitive processes while keeping humans involved where judgment or approval matters.",
      cta,
      nodes: [
        {
          id: "trigger",
          label: "New invoice",
          detail: "Email received",
          status: "done",
          x: 22,
          y: 22,
        },
        {
          id: "extract",
          label: "AI extraction",
          detail: "Fields validated",
          status: "done",
          x: 22,
          y: 62,
        },
        {
          id: "approve",
          label: "Human approval",
          detail: "Finance lead",
          status: "active",
          x: 70,
          y: 42,
        },
        {
          id: "sync",
          label: "Sync to ERP",
          detail: "After approval",
          status: "todo",
          x: 70,
          y: 80,
        },
      ],
      edges: [
        ["trigger", "extract"],
        ["extract", "approve"],
        ["approve", "sync"],
      ],
    },
    {
      id: "improve",
      tabLabel: "Improve",
      stepLabel: "Step 05",
      title: "Improve",
      description:
        "We continuously analyze the system and identify opportunities to make operations faster, smarter, and more scalable.",
      cta,
      nodes: [
        {
          id: "monitor",
          label: "Monitoring",
          detail: "Live metrics",
          status: "done",
          x: 22,
          y: 22,
        },
        {
          id: "analyze",
          label: "Analysis",
          detail: "Weekly review",
          status: "done",
          x: 22,
          y: 62,
        },
        {
          id: "optimize",
          label: "Optimization",
          detail: "2 in progress",
          status: "active",
          x: 70,
          y: 42,
        },
        {
          id: "scale",
          label: "Scale",
          detail: "Next quarter",
          status: "todo",
          x: 70,
          y: 80,
        },
      ],
      edges: [
        ["monitor", "analyze"],
        ["analyze", "optimize"],
        ["optimize", "scale"],
      ],
    },
  ],
} as const satisfies WorkflowContent;

export function getWorkflowContent(): WorkflowContent {
  return workflowContent;
}
